# Generated by Django 4.1.3 on 2022-12-13 12:37

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dirivinglicence",
            name="image",
            field=sorl.thumbnail.fields.ImageField(upload_to="profile_pic"),
        ),
    ]
