# Generated by Django 4.1.3 on 2022-12-13 12:52

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_dirivinglicence_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dirivinglicence",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=["middle", "center"],
                force_format="JPEG",
                keep_meta=True,
                quality=75,
                scale=0.5,
                size=[500, 300],
                upload_to="profile_pic",
            ),
        ),
    ]
