# Generated by Django 4.1.3 on 2022-12-19 13:00

from django.db import migrations, models
import django_resized.forms
import myapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_dirivinglicence_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dirivinglicence",
            name="file",
            field=models.FileField(
                default=" ",
                upload_to="documents/%Y/%m/%d",
                validators=[myapp.validators.validate_file_size],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dirivinglicence",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=["middle", "center"],
                force_format="JPEG",
                keep_meta=True,
                quality=75,
                scale=0.5,
                size=[500, 300],
                upload_to="profile_pic",
            ),
        ),
    ]
